# Generated by Django 5.2.1 on 2025-06-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название подразделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название линии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_downtimes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downtimes.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Простой',
                'verbose_name_plural': 'Простои',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='downtimes.downtime', verbose_name='Простой')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История простоя',
                'verbose_name_plural': 'История простоев',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название причины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='downtimes.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Причина простоя',
                'verbose_name_plural': 'Причины простоев',
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='downtime',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downtimes.downtimereason', verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimes.line', verbose_name='Линия'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название участка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='downtimes.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['line', 'name'],
                'unique_together': {('name', 'line')},
            },
        ),
        migrations.AddField(
            model_name='downtime',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downtimes.section', verbose_name='Участок'),
        ),
    ]
