# Generated by Django 5.2.1 on 2025-06-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downtimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_downtimes', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downtimes.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='downtimehistory',
            name='downtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='downtimes.downtime', verbose_name='Простой'),
        ),
        migrations.AddField(
            model_name='downtimehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='downtimereason',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='downtimes.department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downtimes.downtimereason', verbose_name='Причина'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimes.line', verbose_name='Линия'),
        ),
        migrations.AddField(
            model_name='section',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='downtimes.line', verbose_name='Линия'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downtimes.section', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='shift',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='downtimes.line', verbose_name='Линия'),
        ),
        migrations.AlterUniqueTogether(
            name='downtimereason',
            unique_together={('name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'line')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('line', 'name')},
        ),
    ]
