# Generated by Django 5.0.6 on 2025-06-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtimehistory',
            name='details',
        ),
        migrations.AddField(
            model_name='downtimehistory',
            name='changes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='downtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='downtimes.downtime'),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='downtimehistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
