# Generated by Django 5.2.1 on 2025-06-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downtimes', '0003_remove_downtimehistory_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='downtimes.line', verbose_name='Линия')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='downtimes.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'План производства',
                'verbose_name_plural': 'Планы производства',
                'ordering': ['-date', 'line', 'shift'],
                'unique_together': {('line', 'shift', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукции')),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='Плановое количество')),
                ('completed_quantity', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Позиция плана',
                'verbose_name_plural': 'Позиции плана',
                'ordering': ['start_time'],
            },
        ),
    ]
