# Generated by Django 5.2.1 on 2025-06-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0003_remove_downtimehistory_details_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='product_name',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='downtimes.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ['line', 'name'],
                'unique_together': {('name', 'line')},
            },
        ),
        migrations.AddField(
            model_name='planitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='plans.product', verbose_name='Продукция'),
        ),
    ]
