# Generated by Django 5.2.1 on 2025-06-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_planitem_product_name_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='plans.product', verbose_name='Продукция'),
        ),
    ]
