# Generated by Django 5.2.1 on 2025-06-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_planitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planitem',
            options={'ordering': ['product'], 'verbose_name': 'Позиция плана', 'verbose_name_plural': 'Позиции плана'},
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='start_time',
        ),
    ]
