# Generated by Django 5.2.1 on 2025-06-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_planitem_options_remove_planitem_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='line',
        ),
    ]
