# Generated by Django 5.2.1 on 2025-06-09 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('running', 'Выполняется'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('result', models.TextField(blank=True, verbose_name='Результат выполнения')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Фоновая задача',
                'verbose_name_plural': 'Фоновые задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
