# Generated by Django 5.2.1 on 2025-06-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
